public class Bank_Transaction_Controller {
	/* The purpose of this class is to provide the transaction functionality
	 * for the Bank application.
	 */
    
    public static void subtractFromBalance(ID accountID, Double amount){
        //This method should update the specified account, by subtracting
        //the specified amount from the balance of that account.
        
    }
    
    public static void addToBalance(ID accountID, Double amount){
        //This method should update the specified account, by adding
        //the specified amount to the balance of that account.
    }
    
}