if(true){
    System.debug("Hello"); //This is a code block statement
    System.debug("World");
}

if(true)
    System.Debug(1); //This is a single line statement
    else {
       System.debug(2);
    }

/*
This is a multi-line comment
*/

nothing within // or /*...comment...*/ 
will be commented out

1+6; // REPL evaluates to an Integer data type with value 7

new Account(Name = 'Little Deb'); //Method Invocation (Constructor) example

/* Classes */
public /*access modifier required*/ class /* keyword */ myClass /* name of the class */ {
    //Enter code in this Code Block
    
    //variables require data type & name
    Boolean boo;

    //Declaration vs Instantiation
    boolean boo = true; //Declaration example

    //Methods optionally contain access or definition modifiers
    //Methods & parameters require return type & name...{};
    //Abstract Methods don't require code block
    void myMethod(/* input parameters */ String name, Integer age){
        //Method logic goes hear
    }



}





