public class Bank(){

    public Integer BankId = BID-{0000};
    //private static bankInfo = 'Bankature USA\n777 Trust Ln.,\nChicago, IL 55555'

    public static void class Main(){

        bankName();
        Employee employee = new Employee(List<employee>);
        Customer customer = new Customer(new Account(new Transction(deposit))); //A customer needs to open a new account with a deposit
        
    }
}





